import F1 from './BMI/F1.svg'
import F2 from './BMI/F2.svg'
import F3 from './BMI/F3.svg'
import F4 from './BMI/F4.svg'
import F5 from './BMI/F5.svg'
import M1 from './BMI/M1.svg'
import M2 from './BMI/M2.svg'
import M3 from './BMI/M3.svg'
import M4 from './BMI/M4.svg'
import M5 from './BMI/M5.svg'
import DefaultImage from './images/8b1deecf1843ac90f969831ecb53477e.png'
import Gaitwise from './svg/gaitwise.svg'
import Metalogo from './svg/gaitwise-logo.svg'
import GaitwiseLogo from './svg/gaitwise-logo1.svg'
import SurveyLogo from './svg/survey-svgrepo-com.svg'
import UserLogo from './svg/user-svgrepo-com.svg'

export { DefaultImage, F1, F2, F3, F4, F5, Gaitwise, GaitwiseLogo, M1, M2, M3, M4, M5, Metalogo, SurveyLogo, UserLogo }
